name: number_panel
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^7.3.3
  get_it: ^7.2.0

flutter:
  uses-material-design: true

dev_dependencies: 
  dart_code_metrics: ^4.9.1
  flutter_lints: ^1.0.4
